#!/usr/bin/env bash
# Scaffold a Cargo crate from buf/prost(+tonic) output for Kellnr publish.
set -euo pipefail

OUT="${1:-build/generated/rust}"
SRC_RS="${OUT}/src"
mkdir -p "${SRC_RS}"

ROOT_NAME="$(grep -E 'rootProject.name' settings.gradle | sed -E 's/.*"([^"]+)".*/\1/')"
CRATE_NAME="$(echo "${ROOT_NAME}" | tr '.' '-' | tr '[:upper:]' '[:lower:]')"
VERSION="$(grep -E '^version' gradle.properties | head -1 | sed -E 's/.*=\s*//' | tr -d '[:space:]' | sed 's/-SNAPSHOT//')"
VERSION="${VERSION:-0.1.0}"
if [ -n "${CI_COMMIT_TAG:-}" ]; then
  VERSION="${CI_COMMIT_TAG#v}"
fi

# Prost files are named like tech.maze.dtos.helloworld.models.rs and expect
# sibling modules (super::models). Tonic stubs (*tonic.rs) are include!()'d
# from the companion prost file — do not register them as modules.
mapfile -t files < <(
  find "${SRC_RS}" -type f -name '*.rs' ! -name 'lib.rs' ! -name '*tonic.rs' | sort
)

NEED_TONIC=0
if find "${SRC_RS}" -type f -name '*tonic.rs' | grep -q .; then
  NEED_TONIC=1
fi

{
  echo "// @generated by scripts/rust-crate.sh — do not edit."
  echo "#![allow(dead_code, unused_imports, clippy::all)]"
  echo
  if [ "${#files[@]}" -eq 0 ]; then
    echo "//! DTO crate from ${ROOT_NAME} specs (proto → prost)."
    echo "pub const CRATE_NAME: &str = \"${CRATE_NAME}\";"
    echo "pub const CRATE_VERSION: &str = env!(\"CARGO_PKG_VERSION\");"
  else
    # Group by package prefix (everything before the last dotted segment).
    declare -A GROUPS=()
    for f in "${files[@]}"; do
      rel="${f#${SRC_RS}/}"
      base="${rel%.rs}"
      leaf="${base##*.}"
      prefix="${base%.*}"
      GROUPS["${prefix}"]+="${leaf}|"
    done

    for prefix in $(printf '%s\n' "${!GROUPS[@]}" | sort); do
      mod_path="$(echo "${prefix}" | tr '.' '_' | tr '[:upper:]' '[:lower:]')"
      echo "pub mod ${mod_path} {"
      IFS='|' read -r -a leaves <<< "${GROUPS[$prefix]}"
      for leaf in "${leaves[@]}"; do
        [ -n "${leaf}" ] || continue
        rel="${prefix}.${leaf}.rs"
        echo "    #[path = \"${rel}\"]"
        echo "    pub mod ${leaf};"
        echo "    pub use ${leaf}::*;"
      done
      echo "}"
      echo "pub use ${mod_path}::*;"
      echo
    done
  fi
} > "${SRC_RS}/lib.rs"

DEPS=$'prost = "0.13"\nprost-types = "0.13"\nbytes = "1"'
if [ "${NEED_TONIC}" -eq 1 ]; then
  DEPS+=$'\ntonic = { version = "0.12", default-features = false, features = ["codegen", "transport", "prost"] }\nhttp = "1"\ntokio = { version = "1", features = ["macros", "rt"] }\nasync-trait = "0.1"'
fi

cat > "${OUT}/Cargo.toml" <<TOML
[package]
name = "${CRATE_NAME}"
version = "${VERSION}"
edition = "2021"
description = "Maze DTO crate generated from ${ROOT_NAME} specs"
license = "MIT"
publish = ["maze"]

[dependencies]
${DEPS}

[package.metadata.docs.rs]
all-features = true
TOML

echo "rust crate ready: ${OUT} name=${CRATE_NAME} version=${VERSION} modules=${#files[@]} tonic=${NEED_TONIC}"
