#!/usr/bin/env bash
# Scaffold a Cargo crate from buf/prost output for Kellnr publish.
set -euo pipefail

OUT="${1:-build/generated/rust}"
SRC_RS="${OUT}/src"
mkdir -p "${SRC_RS}"

ROOT_NAME="$(grep -E 'rootProject.name' settings.gradle | sed -E 's/.*"([^"]+)".*/\1/')"
CRATE_NAME="$(echo "${ROOT_NAME}" | tr '.' '-' | tr '[:upper:]' '[:lower:]')"
VERSION="$(grep -E '^version' gradle.properties | head -1 | sed -E 's/.*=\s*//' | tr -d '[:space:]' | sed 's/-SNAPSHOT//')"
VERSION="${VERSION:-0.1.0}"
if [ -n "${CI_COMMIT_TAG:-}" ]; then
  VERSION="${CI_COMMIT_TAG#v}"
fi

mapfile -t files < <(find "${SRC_RS}" -type f -name '*.rs' ! -name 'lib.rs' | sort)

{
  echo "// @generated by scripts/rust-crate.sh — do not edit."
  echo "#![allow(dead_code, unused_imports, clippy::all)]"
  echo
  if [ "${#files[@]}" -eq 0 ]; then
    echo "//! DTO crate from ${ROOT_NAME} specs (proto → prost)."
    echo "pub const CRATE_NAME: &str = \"${CRATE_NAME}\";"
    echo "pub const CRATE_VERSION: &str = env!(\"CARGO_PKG_VERSION\");"
  else
    for f in "${files[@]}"; do
      rel="${f#${SRC_RS}/}"
      mod="$(echo "${rel%.rs}" | tr '/.-' '___' | tr '[:upper:]' '[:lower:]')"
      echo "#[path = \"${rel}\"]"
      echo "mod ${mod};"
      echo "pub use ${mod}::*;"
      echo
    done
  fi
} > "${SRC_RS}/lib.rs"

cat > "${OUT}/Cargo.toml" <<TOML
[package]
name = "${CRATE_NAME}"
version = "${VERSION}"
edition = "2021"
description = "Maze DTO crate generated from ${ROOT_NAME} specs"
license = "MIT"
publish = ["maze"]

[dependencies]
prost = "0.13"
prost-types = "0.13"
bytes = "1"

[package.metadata.docs.rs]
all-features = true
TOML

echo "rust crate ready: ${OUT} name=${CRATE_NAME} version=${VERSION} modules=${#files[@]}"
