# WireGuard client configuration — generated by OpenTofu
# Save to: /etc/wireguard/wg-gitlab.conf (permissions: 600)
# Connect: sudo wg-quick up wg-gitlab
# Disconnect: sudo wg-quick down wg-gitlab
#
# Prerequisites on client:
#   1. Install WireGuard: apt install wireguard (Linux) / brew install wireguard-tools (macOS)
#   2. Add to /etc/hosts: ${server_vpn_ip}  gitlab.internal registry.gitlab.internal
#   3. Trust the self-signed cert (see post_deploy_instructions output)

[Interface]
# Replace with your client's private key (generate with: wg genkey)
PrivateKey = <CLIENT_PRIVATE_KEY>
Address = ${client_vpn_ip}/32

[Peer]
# GitLab server
PublicKey = ${server_public_key}
Endpoint = ${server_endpoint}
# Route only VPN subnet traffic through the tunnel (split-tunnel)
# To route ALL traffic: AllowedIPs = 0.0.0.0/0, ::/0
AllowedIPs = ${vpn_subnet}
# Keep connection alive through NAT/firewalls
PersistentKeepalive = 25
