variable "cluster_name" {
  description = "Name of the Kubernetes cluster"
  type        = string
}

variable "environment" {
  description = "Environment name"
  type        = string
}

variable "namespace" {
  description = "Namespace for WireGuard deployment"
  type        = string
  default     = "wireguard"
}

variable "vpn_subnet" {
  description = "WireGuard VPN subnet CIDR"
  type        = string
  default     = "10.8.0.0/24"
}

variable "allowed_ips" {
  description = "Comma-separated AllowedIPs pushed to peers (must include VPN subnet plus ClusterIP/pod ranges so clients can reach platform services through the tunnel)"
  type        = string
  default     = ""
}

variable "server_port" {
  description = "WireGuard UDP listen port"
  type        = number
  default     = 51820
}

variable "server_url" {
  description = "Public endpoint hostname or IP for WireGuard clients (SERVERURL env var)"
  type        = string
  default     = "127.0.0.1"
}

variable "peers" {
  description = "Comma-separated list of peer names (configs auto-generated by linuxserver/wireguard)"
  type        = string
  default     = "admin,developer"
}

variable "service_type" {
  description = "Kubernetes service type (NodePort for local/kind, LoadBalancer for production)"
  type        = string
  default     = "NodePort"
}

variable "node_port" {
  description = "NodePort for WireGuard UDP (when service_type = NodePort)"
  type        = number
  default     = 31820
}

variable "storage_size" {
  description = "PVC size for WireGuard configuration and generated peer configs"
  type        = string
  default     = "1Gi"
}

variable "storage_class" {
  description = "StorageClass for WireGuard PVC. Empty uses cluster default."
  type        = string
  default     = ""
}
